Task 4
widgetev/ProPractic pull request #3
Opened 2024-10-05 08:16 UTC by widgetev

***Задание 4***

- [X] Разверните локально postgresql БД, создайте таблицу users (id bigserial primary key, username varchar(255) unique);

- [X] Создайте Maven проект и подключите к нему: драйвер postgresql, hickaricp, spring context.

- [X] Создайте пул соединений в виде Spring бина

- [X] Создайте класс User (Long id, String username)

- [ ] Реализуйте в виде бина класс UserDao который позволяет выполнять CRUD операции над пользователями

- [ ] Реализуйте в виде бина UserService, который позволяет: создавать, удалять, получать одного, получать всех пользователей из базы данных

- [ ] Создайте Spring Context, получите из него бин UserService и выполните все возможные операции

2024-10-08 08:49 UTC, Alexandr056 requested changes
исправте пож-та инжект контекста… 
пл точно лишний

2024-10-08 08:49 UTC, Alexandr056 commented on src/main/java/org/example/task_4/db/ConnectionPool.java
> +    List<Connection> connectionList= new ArrayList<>(); //Пулл подразумевает несколько соединений. Но я с одинм поработаю
тогда стоило ли изобретать пул? :)
просто Connection и все

2024-10-08 08:49 UTC, Alexandr056 commented on src/main/java/org/example/task_4/db/UserDAO.java
> +    private ConnectionPool connectionPool;
во первых лучше сделать final
во вторых зачем ? если следом идет connection

2024-10-08 08:49 UTC, Alexandr056 commented on src/main/java/org/example/task_4/db/UserDAO.java
> +    public UserDAO(GenericApplicationContext context, ConnectionPool connectionPool) throws SQLException, ClassNotFoundException {
а вот это точно большая ошибка, инжектить в объект, который в контексте, сам контекст, что бы достать из контекста что-то

2024-10-08 08:49 UTC, Alexandr056 commented on src/main/java/org/example/task_4/db/UserDAO.java
> +//    void update(Users e) throws SQLException {
закомментированный код

2024-10-08 10:06 UTC, widgetev commented on src/main/java/org/example/task_4/db/ConnectionPool.java
> +    List<Connection> connectionList= new ArrayList<>(); //Пулл подразумевает несколько соединений. Но я с одинм поработаю
В задании сказано сделать пул. Может смысл этого будет раскрыт в следующих задаинях :))

2024-10-08 10:06 UTC, widgetev commented on src/main/java/org/example/task_4/db/UserDAO.java
> +    private ConnectionPool connectionPool;
ОК

2024-10-08 10:07 UTC, widgetev commented on src/main/java/org/example/task_4/db/UserDAO.java
> +    public UserDAO(GenericApplicationContext context, ConnectionPool connectionPool) throws SQLException, ClassNotFoundException {
Ну да, что-то намудрил. Исправил

2024-10-10 11:10 UTC, Alexandr056 commented on src/main/java/org/example/task_4/db/ConnectionPool.java
> +    List<Connection> connectionList= new ArrayList<>(); //Пулл подразумевает несколько соединений. Но я с одинм поработаю
а, ок.

2024-10-10 11:12 UTC, Alexandr056 approved these changes
ок

2024-10-10 11:12 UTC, Alexandr056 commented on src/main/java/org/example/task_4/UserService.java
> +    UserDAO userDAO;
private final

2024-10-10 11:12 UTC, Alexandr056 commented on src/main/java/org/example/task_4/db/Users.java
> +    private String username;
сначала поля

2024-10-10 11:12 UTC, Alexandr056 commented on src/main/java/org/example/task_4/db/Users.java
> +    public Users(String username) {
потом конструктор

2024-10-12 08:48 UTC, merged